### ISSUE TITLE
black screen when used as AAR lib

### ISSUE THREAD

**Issue by UgurIster** [Unity-Technologies/arfoundation-samples#53]
When i build from Unity as apk or also when deployed directly from Unity made AndroidProject
the AR(Core) scene/view works but when instead of deploying the apk right from the Unity made AndroidProject i deploy that as AAR lib and use it in another AndroidProject then in the AR scene the cam/screen stays black (it only shows Unity UI)

When using Unity content as AAR lib i have it in a UnityHolderActivity and there it then throws the error:
Unable to find UnityARCore
UnityHolderActivity E/Unity: DllNotFoundException: UnityARCore
    at (wrapper managed-to-native) UnityEngine.XR.ARCore.Api:UnityARCore_setCameraPermissionProvider (UnityEngine.XR.ARCore.Api/CameraPermissionRequestProvider)
      at UnityEngine.XR.ARCore.ARCoreCameraExtension.Register () [0x00000] in <filename unknown>:0

**Comment by UgurIster** [comment]
now i tried adding
UnityARCore.aar
unityandroidpermissions.aar
arcore_client.aar 
as module to the other AndroidProject (into which i also add the unity deployed android project deployed as .aar lib)
and also added them in the app build gradle like
    implementation project(':UnityARCore')
    implementation project(':unityandroidpermissions')
    implementation project(':arcore_client')

and then i don't get 
Unable to find UnityARCore
anymore but instead get:


10-03 03:50:13.023 26373-26450/com.test..UnityHolderActivity E/ARCore-ArCoreApkJniAdapter: Exception details:
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/ar/core/a;
        at com.google.ar.core.ArCoreApk$Availability.<clinit>(Unknown Source:0)
        at com.google.ar.core.B.a(Unknown Source:28)
        at com.google.ar.core.h.checkAvailability(Unknown Source:40)
        at com.google.ar.core.ArCoreApkJniAdapter.checkAvailability(Unknown Source:27)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:23)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:94)
        at android.os.MessageQueue.next(MessageQueue.java:394)
        at android.os.Looper.loop(Looper.java:142)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:48)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.ar.core.a" on path: DexPathList[[zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/base.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_dependencies_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_resources_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_0_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_1_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_2_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_3_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_4_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_5_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_6_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_7_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_8_apk.apk", zip file "/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/lib/arm, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/base.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.ar.core.ArCoreApk$Availability.<clinit>(Unknown Source:0) 
        at com.google.ar.core.B.a(Unknown Source:28) 
        at com.google.ar.core.h.checkAvailability(Unknown Source:40) 
        at com.google.ar.core.ArCoreApkJniAdapter.checkAvailability(Unknown Source:27) 
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
        at com.unity3d.player.UnityPlayer.c(Unknown Source:23) 
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:94) 
        at android.os.MessageQueue.next(MessageQueue.java:394) 
        at android.os.Looper.loop(Looper.java:142) 
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:48) 
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm) /data/app/co.getrad.radical-vywcNM8qHuK5qPu-2t5Row==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
10-03 03:50:13.025 26373-26450/co.getrad.radical.UnityHolderActivity E/ARCore-ArCoreApkJniAdapter:     at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
        at android.app.LoadedApk.getResources(LoadedApk.java:942)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5937)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by UgurIster** [comment]
has anyone from the UT team tried using AR Foundation on Android with a unity deployed Android project then deployed as AAR lib and used in a native project?
Not sure why it can't find Lcom/google/ar/core/a
after iu already added arcore_client.aar etc

**Comment by tdmowrer** [comment]
I think this is related to a fixed issue with [Android App Bundles (aab)](https://issuetracker.unity3d.com/issues/android-unity-arcore-failed-to-register-lifecycle-provider-input-subsystem-will-be-unavailable-thrown-on-aabs).

**Comment by harisf3** [comment]
still facing this issue in Android studio 4.0 with .aar

**Comment by tdmowrer** [comment]
@harisf3 This is an old thread and unlikely to be the same root cause. Could you please open a new issue for this?
